# Generated by Django 4.0 on 2022-01-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_description', models.CharField(blank=True, max_length=255)),
                ('category_slug', models.CharField(max_length=100, unique=True)),
                ('category_imge', models.ImageField(blank=True, upload_to='Category')),
            ],
        ),
    ]
